import type { ZenColorsPreset } from './types';

/** Red/crimson + purple zen colors */
export const ember: ZenColorsPreset = {
  background: '#0a0a0a',
  blur: 80,
  blendMode: 'lighter',
  blobs: [
    {
      id: 'ember-red',
      color: '#cc0033',
      x: 65,
      y: 40,
      size: 45,
      opacity: 0.9,
      shape: 'ellipse',
      scaleX: 1.6,
      scaleY: 0.9,
      rotation: -25,
      animation: { type: 'drift', speed: 0.6, range: 8, phase: 0 },
    },
    {
      id: 'ember-crimson',
      color: '#ff1155',
      x: 75,
      y: 55,
      size: 35,
      opacity: 0.8,
      shape: 'ellipse',
      scaleX: 1.3,
      scaleY: 0.8,
      rotation: 15,
      animation: { type: 'breathe', speed: 0.5, range: 10, phase: 90 },
    },
    {
      id: 'ember-purple',
      color: '#8800cc',
      x: 80,
      y: 75,
      size: 30,
      opacity: 0.85,
      shape: 'triangle',
      rotation: 30,
      animation: { type: 'drift', speed: 0.4, range: 12, phase: 180 },
    },
    {
      id: 'ember-pink',
      color: '#ff88aa',
      x: 85,
      y: 35,
      size: 25,
      opacity: 0.5,
      shape: 'beam',
      scaleX: 2.0,
      scaleY: 0.6,
      rotation: -40,
      animation: { type: 'wander', speed: 0.3, range: 6 },
    },
  ],
};

/** Amber/orange warm tones */
export const amber: ZenColorsPreset = {
  background: '#0a0a0a',
  blur: 80,
  blendMode: 'lighter',
  blobs: [
    {
      id: 'amber-core',
      color: '#cc8800',
      x: 68,
      y: 35,
      size: 40,
      opacity: 0.85,
      shape: 'ellipse',
      scaleX: 1.4,
      scaleY: 0.85,
      rotation: -30,
      animation: { type: 'drift', speed: 0.5, range: 10, phase: 0 },
    },
    {
      id: 'amber-orange',
      color: '#ff4400',
      x: 78,
      y: 65,
      size: 38,
      opacity: 0.9,
      shape: 'ellipse',
      scaleX: 1.2,
      scaleY: 1.0,
      rotation: 20,
      animation: { type: 'breathe', speed: 0.4, range: 8, phase: 120 },
    },
    {
      id: 'amber-gold',
      color: '#ffaa33',
      x: 72,
      y: 50,
      size: 30,
      opacity: 0.6,
      shape: 'beam',
      scaleX: 2.2,
      scaleY: 0.5,
      rotation: -50,
      animation: { type: 'drift', speed: 0.6, range: 6, phase: 45 },
    },
    {
      id: 'amber-cream',
      color: '#ffcc88',
      x: 88,
      y: 30,
      size: 22,
      opacity: 0.5,
      shape: 'circle',
      animation: { type: 'wander', speed: 0.3, range: 5 },
    },
  ],
};

/** Blue/cyan zen colors */
export const glacier: ZenColorsPreset = {
  background: '#050510',
  blur: 80,
  blendMode: 'lighter',
  blobs: [
    {
      id: 'glacier-blue',
      color: '#0044ff',
      x: 65,
      y: 45,
      size: 42,
      opacity: 0.9,
      shape: 'ellipse',
      scaleX: 1.5,
      scaleY: 0.8,
      rotation: -20,
      animation: { type: 'drift', speed: 0.5, range: 10, phase: 0 },
    },
    {
      id: 'glacier-cyan',
      color: '#00bbff',
      x: 80,
      y: 65,
      size: 35,
      opacity: 0.85,
      shape: 'beam',
      scaleX: 1.8,
      scaleY: 0.7,
      rotation: 30,
      animation: { type: 'breathe', speed: 0.4, range: 12, phase: 60 },
    },
    {
      id: 'glacier-sky',
      color: '#66ddff',
      x: 85,
      y: 40,
      size: 25,
      opacity: 0.6,
      shape: 'ellipse',
      scaleX: 1.3,
      scaleY: 0.9,
      rotation: -45,
      animation: { type: 'drift', speed: 0.6, range: 8, phase: 180 },
    },
    {
      id: 'glacier-deep',
      color: '#0022aa',
      x: 60,
      y: 60,
      size: 30,
      opacity: 0.7,
      shape: 'circle',
      animation: { type: 'wander', speed: 0.3, range: 7 },
    },
  ],
};

/** Muted amber + magenta */
export const subtle: ZenColorsPreset = {
  background: '#0c0c10',
  blur: 100,
  blendMode: 'lighter',
  blobs: [
    {
      id: 'subtle-amber',
      color: '#aa7722',
      x: 50,
      y: 70,
      size: 35,
      opacity: 0.5,
      shape: 'circle',
      animation: { type: 'drift', speed: 0.3, range: 6, phase: 0 },
    },
    {
      id: 'subtle-magenta',
      color: '#881144',
      x: 75,
      y: 25,
      size: 30,
      opacity: 0.45,
      shape: 'ellipse',
      scaleX: 1.2,
      scaleY: 0.9,
      rotation: 10,
      animation: { type: 'breathe', speed: 0.25, range: 8, phase: 90 },
    },
    {
      id: 'subtle-warm',
      color: '#664400',
      x: 40,
      y: 55,
      size: 25,
      opacity: 0.35,
      shape: 'circle',
      animation: { type: 'wander', speed: 0.2, range: 5 },
    },
  ],
};

/** Green/teal/purple northern lights */
export const aurora: ZenColorsPreset = {
  background: '#050510',
  blur: 90,
  blendMode: 'lighter',
  blobs: [
    {
      id: 'aurora-green',
      color: '#00ff88',
      x: 30,
      y: 40,
      size: 40,
      opacity: 0.7,
      shape: 'ellipse',
      scaleX: 0.7,
      scaleY: 1.8,
      rotation: 5,
      animation: { type: 'drift', speed: 0.4, range: 15, phase: 0 },
    },
    {
      id: 'aurora-teal',
      color: '#00ccaa',
      x: 55,
      y: 30,
      size: 35,
      opacity: 0.65,
      shape: 'ellipse',
      scaleX: 0.6,
      scaleY: 1.6,
      rotation: -10,
      animation: { type: 'wander', speed: 0.3, range: 12 },
    },
    {
      id: 'aurora-purple',
      color: '#7700cc',
      x: 75,
      y: 55,
      size: 30,
      opacity: 0.6,
      shape: 'beam',
      scaleX: 0.5,
      scaleY: 2.0,
      rotation: 8,
      animation: { type: 'breathe', speed: 0.35, range: 10, phase: 120 },
    },
    {
      id: 'aurora-mint',
      color: '#44ffaa',
      x: 45,
      y: 60,
      size: 20,
      opacity: 0.5,
      shape: 'scalene',
      scaleX: 0.8,
      scaleY: 1.5,
      rotation: -5,
      animation: { type: 'orbit', speed: 0.2, range: 8, phase: 45 },
    },
  ],
};

/** Orange/pink/purple sunset */
export const sunset: ZenColorsPreset = {
  background: '#0a0508',
  blur: 85,
  blendMode: 'lighter',
  blobs: [
    {
      id: 'sunset-orange',
      color: '#ff6600',
      x: 30,
      y: 60,
      size: 40,
      opacity: 0.8,
      shape: 'ellipse',
      scaleX: 1.8,
      scaleY: 0.7,
      rotation: 0,
      animation: { type: 'drift', speed: 0.4, range: 10, phase: 0 },
    },
    {
      id: 'sunset-pink',
      color: '#ff3388',
      x: 55,
      y: 45,
      size: 35,
      opacity: 0.75,
      shape: 'ellipse',
      scaleX: 1.6,
      scaleY: 0.8,
      rotation: 10,
      animation: { type: 'breathe', speed: 0.35, range: 12, phase: 90 },
    },
    {
      id: 'sunset-purple',
      color: '#9933ff',
      x: 75,
      y: 35,
      size: 30,
      opacity: 0.7,
      shape: 'beam',
      scaleX: 2.0,
      scaleY: 0.5,
      rotation: -15,
      animation: { type: 'drift', speed: 0.5, range: 8, phase: 180 },
    },
    {
      id: 'sunset-gold',
      color: '#ffaa00',
      x: 20,
      y: 70,
      size: 25,
      opacity: 0.5,
      shape: 'ellipse',
      scaleX: 1.5,
      scaleY: 0.6,
      rotation: 5,
      animation: { type: 'wander', speed: 0.3, range: 6 },
    },
  ],
};

/** Deep blue/teal/cyan ocean */
export const ocean: ZenColorsPreset = {
  background: '#020810',
  blur: 90,
  blendMode: 'lighter',
  blobs: [
    {
      id: 'ocean-deep',
      color: '#003366',
      x: 40,
      y: 50,
      size: 50,
      opacity: 0.8,
      shape: 'circle',
      animation: { type: 'drift', speed: 0.3, range: 12, phase: 0 },
    },
    {
      id: 'ocean-teal',
      color: '#008888',
      x: 65,
      y: 40,
      size: 35,
      opacity: 0.7,
      shape: 'ring',
      animation: { type: 'breathe', speed: 0.4, range: 10, phase: 60 },
    },
    {
      id: 'ocean-cyan',
      color: '#00bbcc',
      x: 55,
      y: 65,
      size: 28,
      opacity: 0.6,
      shape: 'ring',
      animation: { type: 'wander', speed: 0.25, range: 8 },
    },
    {
      id: 'ocean-foam',
      color: '#88ddee',
      x: 75,
      y: 55,
      size: 18,
      opacity: 0.4,
      shape: 'triangle',
      rotation: 25,
      animation: { type: 'orbit', speed: 0.2, range: 6, phase: 120 },
    },
  ],
};

/** Bright vibrant neon multi-color */
export const neon: ZenColorsPreset = {
  background: '#050505',
  blur: 70,
  blendMode: 'lighter',
  blobs: [
    {
      id: 'neon-magenta',
      color: '#ff00ff',
      x: 25,
      y: 40,
      size: 30,
      opacity: 0.85,
      shape: 'beam',
      scaleX: 1.8,
      scaleY: 0.6,
      rotation: 45,
      animation: { type: 'orbit', speed: 0.5, range: 15, phase: 0 },
    },
    {
      id: 'neon-cyan',
      color: '#00ffff',
      x: 70,
      y: 35,
      size: 28,
      opacity: 0.85,
      shape: 'pentagon',
      animation: { type: 'orbit', speed: 0.5, range: 15, phase: 120 },
    },
    {
      id: 'neon-yellow',
      color: '#ffff00',
      x: 50,
      y: 65,
      size: 25,
      opacity: 0.8,
      shape: 'square',
      rotation: 15,
      animation: { type: 'orbit', speed: 0.5, range: 15, phase: 240 },
    },
    {
      id: 'neon-green',
      color: '#00ff44',
      x: 40,
      y: 50,
      size: 22,
      opacity: 0.7,
      shape: 'beam',
      scaleX: 2.0,
      scaleY: 0.4,
      rotation: 60,
      animation: { type: 'drift', speed: 0.6, range: 10, phase: 90 },
    },
    {
      id: 'neon-red',
      color: '#ff0044',
      x: 60,
      y: 50,
      size: 22,
      opacity: 0.7,
      shape: 'ellipse',
      scaleX: 1.2,
      scaleY: 1.4,
      rotation: 15,
      animation: { type: 'drift', speed: 0.6, range: 10, phase: 270 },
    },
  ],
};

/** All presets as a record for easy iteration */
export const presets = {
  ember,
  amber,
  glacier,
  subtle,
  aurora,
  sunset,
  ocean,
  neon,
} as const;

export type PresetName = keyof typeof presets;
